name: offline_payments_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 👉 App dependencies
  sqflite: ^2.3.0          # SQLite storage
  path_provider: ^2.1.2    # Helps find local paths
  nearby_connections: ^4.3.0 # Peer-to-peer over Nearby
  uuid: ^4.2.1             # Generate unique IDs
  intl: ^0.18.0            # Date/time formatting (for HistoryScreen)
  decimal: ^2.3.3          # High-precision decimal numbers
  device_info_plus: ^10.1.0 # ✅ Added for device info
  permission_handler: ^11.3.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
